const data = {
   users : [
    {
      name: "System Administrator",
      email: "admin@gmail.com",
      password: "e@12",   
      address: "123 Admin St.",
      phone: "+11234567890",
      role: "admin",
    },
    {
      name: "Receptionist One",
      email: "reception@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    }, 
    {
      name: "Dr. John Doe",
      email: "johndoe@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist One",
      email: "reception1@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. John Doe",
      email: "johndoe1@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist One",
      email: "reception2@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. John Doe",
      email: "johndoe2@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist One",
      email: "reception3@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. John Doe",
      email: "johndoe3@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist One",
      email: "reception4@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. John Doe",
      email: "johndoe4@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist amin",
      email: "reception5@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Yousuf",
      email: "johndoe5@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist Jubair",
      email: "reception6@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Talha",
      email: "johndoe6@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist Karim",
      email: "reception7@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Mahim",
      email: "johndoe7@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
     {
      name: "Receptionist Two",
      email: "reception8@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Fahim",
      email: "johndoe8@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
    {
      name: "Receptionist Two",
      email: "reception9@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Fahim",
      email: "johndoe9@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },
    {
      name: "Receptionist Two",
      email: "reception11@hospital.com",
      password: "RecepPass123",
      address: "456 Frontdesk Rd.",
      phone: "+11987654321",
      role: "receptionist",
    },
    {
      name: "Dr. Fahim",
      email: "johndoe11@hospital.com",
      password: "DoctorPass123",
      address: "789 Clinic Ave.",
      phone: "+11012349876",
      role: "doctor",
    },

  ]
}

module.exports = data;